// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// El reloj vectorial es un mapa de ID_Nodo -> Contador
type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      map[string]int64       `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetVersions() map[string]int64 {
	if x != nil {
		return x.Versions
	}
	return nil
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Clock         *VectorClock           `protobuf:"bytes,3,opt,name=clock,proto3" json:"clock,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Para desempate (Last Writer Wins)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Review) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *Review) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Request/Response para Escritura
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *WriteRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	WrittenAtNode string                 `protobuf:"bytes,2,opt,name=written_at_node,json=writtenAtNode,proto3" json:"written_at_node,omitempty"` // Para RYW: saber dónde se escribió
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *WriteResponse) GetWrittenAtNode() string {
	if x != nil {
		return x.WrittenAtNode
	}
	return ""
}

// Request/Response para Lectura
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	PreferredNode string                 `protobuf:"bytes,2,opt,name=preferred_node,json=preferredNode,proto3" json:"preferred_node,omitempty"` // Para RYW: intentar leer de aquí
	MinClock      *VectorClock           `protobuf:"bytes,3,opt,name=min_clock,json=minClock,proto3" json:"min_clock,omitempty"`                // Para Monotonic: no aceptar menos que esto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *ReadRequest) GetPreferredNode() string {
	if x != nil {
		return x.PreferredNode
	}
	return ""
}

func (x *ReadRequest) GetMinClock() *VectorClock {
	if x != nil {
		return x.MinClock
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	SourceNode    string                 `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *ReadResponse) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

// Replicación entre Datanodes
type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	SenderNodeId  string                 `protobuf:"bytes,2,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicateRequest) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *ReplicateRequest) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x05proto\"\x88\x01\n" +
	"\vVectorClock\x12<\n" +
	"\bversions\x18\x01 \x03(\v2 .proto.VectorClock.VersionsEntryR\bversions\x1a;\n" +
	"\rVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"z\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12(\n" +
	"\x05clock\x18\x03 \x01(\v2\x12.proto.VectorClockR\x05clock\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"E\n" +
	"\fWriteRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"T\n" +
	"\rWriteResponse\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\tR\breviewId\x12&\n" +
	"\x0fwritten_at_node\x18\x02 \x01(\tR\rwrittenAtNode\"\x82\x01\n" +
	"\vReadRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\tR\breviewId\x12%\n" +
	"\x0epreferred_node\x18\x02 \x01(\tR\rpreferredNode\x12/\n" +
	"\tmin_clock\x18\x03 \x01(\v2\x12.proto.VectorClockR\bminClock\"V\n" +
	"\fReadResponse\x12%\n" +
	"\x06review\x18\x01 \x01(\v2\r.proto.ReviewR\x06review\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\"_\n" +
	"\x10ReplicateRequest\x12%\n" +
	"\x06review\x18\x01 \x01(\v2\r.proto.ReviewR\x06review\x12$\n" +
	"\x0esender_node_id\x18\x02 \x01(\tR\fsenderNodeId\"\a\n" +
	"\x05Empty2\xa6\x02\n" +
	"\x12DistributedService\x129\n" +
	"\fCreateReview\x12\x13.proto.WriteRequest\x1a\x14.proto.WriteResponse\x124\n" +
	"\tGetReview\x12\x12.proto.ReadRequest\x1a\x13.proto.ReadResponse\x126\n" +
	"\tWriteData\x12\x13.proto.WriteRequest\x1a\x14.proto.WriteResponse\x123\n" +
	"\bReadData\x12\x12.proto.ReadRequest\x1a\x13.proto.ReadResponse\x122\n" +
	"\tReplicate\x12\x17.proto.ReplicateRequest\x1a\f.proto.EmptyB\tZ\a./protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_service_proto_goTypes = []any{
	(*VectorClock)(nil),      // 0: proto.VectorClock
	(*Review)(nil),           // 1: proto.Review
	(*WriteRequest)(nil),     // 2: proto.WriteRequest
	(*WriteResponse)(nil),    // 3: proto.WriteResponse
	(*ReadRequest)(nil),      // 4: proto.ReadRequest
	(*ReadResponse)(nil),     // 5: proto.ReadResponse
	(*ReplicateRequest)(nil), // 6: proto.ReplicateRequest
	(*Empty)(nil),            // 7: proto.Empty
	nil,                      // 8: proto.VectorClock.VersionsEntry
}
var file_proto_service_proto_depIdxs = []int32{
	8,  // 0: proto.VectorClock.versions:type_name -> proto.VectorClock.VersionsEntry
	0,  // 1: proto.Review.clock:type_name -> proto.VectorClock
	0,  // 2: proto.ReadRequest.min_clock:type_name -> proto.VectorClock
	1,  // 3: proto.ReadResponse.review:type_name -> proto.Review
	1,  // 4: proto.ReplicateRequest.review:type_name -> proto.Review
	2,  // 5: proto.DistributedService.CreateReview:input_type -> proto.WriteRequest
	4,  // 6: proto.DistributedService.GetReview:input_type -> proto.ReadRequest
	2,  // 7: proto.DistributedService.WriteData:input_type -> proto.WriteRequest
	4,  // 8: proto.DistributedService.ReadData:input_type -> proto.ReadRequest
	6,  // 9: proto.DistributedService.Replicate:input_type -> proto.ReplicateRequest
	3,  // 10: proto.DistributedService.CreateReview:output_type -> proto.WriteResponse
	5,  // 11: proto.DistributedService.GetReview:output_type -> proto.ReadResponse
	3,  // 12: proto.DistributedService.WriteData:output_type -> proto.WriteResponse
	5,  // 13: proto.DistributedService.ReadData:output_type -> proto.ReadResponse
	7,  // 14: proto.DistributedService.Replicate:output_type -> proto.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
