// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistributedService_CreateReview_FullMethodName = "/proto.DistributedService/CreateReview"
	DistributedService_GetReview_FullMethodName    = "/proto.DistributedService/GetReview"
	DistributedService_WriteData_FullMethodName    = "/proto.DistributedService/WriteData"
	DistributedService_ReadData_FullMethodName     = "/proto.DistributedService/ReadData"
	DistributedService_Replicate_FullMethodName    = "/proto.DistributedService/Replicate"
)

// DistributedServiceClient is the client API for DistributedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistributedServiceClient interface {
	// Cliente -> Coordinador
	CreateReview(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	GetReview(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Coordinador -> Datanode (o Cliente -> Datanode indirecto)
	WriteData(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	ReadData(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Datanode -> Datanode
	Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*Empty, error)
}

type distributedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributedServiceClient(cc grpc.ClientConnInterface) DistributedServiceClient {
	return &distributedServiceClient{cc}
}

func (c *distributedServiceClient) CreateReview(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, DistributedService_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedServiceClient) GetReview(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, DistributedService_GetReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedServiceClient) WriteData(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, DistributedService_WriteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedServiceClient) ReadData(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, DistributedService_ReadData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedServiceClient) Replicate(ctx context.Context, in *ReplicateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DistributedService_Replicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributedServiceServer is the server API for DistributedService service.
// All implementations must embed UnimplementedDistributedServiceServer
// for forward compatibility.
type DistributedServiceServer interface {
	// Cliente -> Coordinador
	CreateReview(context.Context, *WriteRequest) (*WriteResponse, error)
	GetReview(context.Context, *ReadRequest) (*ReadResponse, error)
	// Coordinador -> Datanode (o Cliente -> Datanode indirecto)
	WriteData(context.Context, *WriteRequest) (*WriteResponse, error)
	ReadData(context.Context, *ReadRequest) (*ReadResponse, error)
	// Datanode -> Datanode
	Replicate(context.Context, *ReplicateRequest) (*Empty, error)
	mustEmbedUnimplementedDistributedServiceServer()
}

// UnimplementedDistributedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistributedServiceServer struct{}

func (UnimplementedDistributedServiceServer) CreateReview(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedDistributedServiceServer) GetReview(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReview not implemented")
}
func (UnimplementedDistributedServiceServer) WriteData(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteData not implemented")
}
func (UnimplementedDistributedServiceServer) ReadData(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadData not implemented")
}
func (UnimplementedDistributedServiceServer) Replicate(context.Context, *ReplicateRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedDistributedServiceServer) mustEmbedUnimplementedDistributedServiceServer() {}
func (UnimplementedDistributedServiceServer) testEmbeddedByValue()                            {}

// UnsafeDistributedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistributedServiceServer will
// result in compilation errors.
type UnsafeDistributedServiceServer interface {
	mustEmbedUnimplementedDistributedServiceServer()
}

func RegisterDistributedServiceServer(s grpc.ServiceRegistrar, srv DistributedServiceServer) {
	// If the following call pancis, it indicates UnimplementedDistributedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistributedService_ServiceDesc, srv)
}

func _DistributedService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedServiceServer).CreateReview(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedService_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedServiceServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedService_GetReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedServiceServer).GetReview(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedService_WriteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedServiceServer).WriteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedService_WriteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedServiceServer).WriteData(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedService_ReadData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedServiceServer).ReadData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedService_ReadData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedServiceServer).ReadData(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedService_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedServiceServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedService_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedServiceServer).Replicate(ctx, req.(*ReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistributedService_ServiceDesc is the grpc.ServiceDesc for DistributedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistributedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DistributedService",
	HandlerType: (*DistributedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReview",
			Handler:    _DistributedService_CreateReview_Handler,
		},
		{
			MethodName: "GetReview",
			Handler:    _DistributedService_GetReview_Handler,
		},
		{
			MethodName: "WriteData",
			Handler:    _DistributedService_WriteData_Handler,
		},
		{
			MethodName: "ReadData",
			Handler:    _DistributedService_ReadData_Handler,
		},
		{
			MethodName: "Replicate",
			Handler:    _DistributedService_Replicate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
